/**
 * Kana pronunciation playback.
 *
 * Clips are bundled assets — a native speaker saying one mora — keyed by kana
 * glyph. Call sites are tap handlers in the middle of a lesson, so the whole
 * surface is built to be un-awaited and un-catchable: nothing here rejects, and
 * nothing here blocks the UI.
 *
 * Recordings by Kaori sensei — see assets/audio/kana/ATTRIBUTION.md. The clips
 * and the glyph map are generated by scripts/build-kana-audio.py.
 */

import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';

import { KANA_AUDIO } from './kanaAudioAssets';

/**
 * How many native players to keep alive at once.
 *
 * Each cached player holds a native instance, so this is not free — but a
 * lesson revisits the same handful of kana constantly, and re-creating a player
 * per tap adds audible latency. Evicting least-recently-used past this point
 * keeps a practice session's working set resident without unbounded growth.
 */
const MAX_CACHED_PLAYERS = 32;

/** Least-recently-used last: Map preserves insertion order, so re-inserting promotes. */
const players = new Map<string, AudioPlayer>();

let audioMode: Promise<void> | null = null;
let nowPlaying: AudioPlayer | null = null;

/**
 * Configure the audio session once, lazily.
 *
 * `playsInSilentMode` is the one that matters: without it iOS silences playback
 * whenever the ring switch is off, which would make "Hear it" look broken for
 * anyone who keeps their phone on silent. Ducking rather than interrupting
 * leaves the learner's own music running underneath.
 */
function ensureAudioMode(): Promise<void> {
  audioMode ??= setAudioModeAsync({
    playsInSilentMode: true,
    shouldPlayInBackground: false,
    interruptionMode: 'duckOthers',
  }).catch(() => {
    // A failed session config is not worth failing playback over — audio may
    // still play fine. Clear it so a later call can retry.
    audioMode = null;
  });
  return audioMode;
}

function acquire(glyph: string): AudioPlayer | null {
  const cached = players.get(glyph);
  if (cached) {
    // Re-insert to mark most-recently-used.
    players.delete(glyph);
    players.set(glyph, cached);
    return cached;
  }

  const asset = KANA_AUDIO[glyph];
  if (asset === undefined) {
    return null;
  }

  const player = createAudioPlayer(asset);
  players.set(glyph, player);

  while (players.size > MAX_CACHED_PLAYERS) {
    const [oldestGlyph, oldest] = players.entries().next().value as [string, AudioPlayer];
    players.delete(oldestGlyph);
    if (oldest !== nowPlaying) {
      // remove() releases the native player; expo-audio leaks it otherwise.
      try {
        oldest.remove();
      } catch {
        // Already released, or the module is torn down. Nothing to do.
      }
    }
  }

  return player;
}

async function start(glyph: string): Promise<void> {
  await ensureAudioMode();

  const player = acquire(glyph);
  if (!player) {
    return;
  }

  if (nowPlaying && nowPlaying !== player) {
    // Tapping a second kana replaces the first rather than layering over it.
    try {
      nowPlaying.pause();
    } catch {
      // Previous player was already released; harmless.
    }
  }
  nowPlaying = player;

  // A cached player is parked wherever it finished, so rewind before replaying.
  await player.seekTo(0);
  player.play();
}

/**
 * Play the clip for a kana glyph.
 *
 * Resolves immediately — playback continues in the background — and never
 * rejects. A missing clip, a decode failure or a torn-down audio session all
 * end in silence rather than an error, because the caller is a tap handler
 * mid-lesson and an unhandled rejection there would break practice over a
 * missing sound file.
 */
export function playKana(glyph: string): Promise<void> {
  void start(glyph).catch(() => {
    // Deliberately swallowed — see doc comment.
  });
  return Promise.resolve();
}

/**
 * Warm the cache for kana about to appear, so the first tap has no load delay.
 *
 * Resolves when the players exist, and never rejects. Preloading more than
 * MAX_CACHED_PLAYERS glyphs is safe but pointless — the earliest are evicted
 * before they are ever heard.
 */
export function preloadKana(glyphs: string[]): Promise<void> {
  try {
    void ensureAudioMode();
    for (const glyph of glyphs) {
      acquire(glyph);
    }
  } catch {
    // Preloading is an optimisation; failing it must not surface.
  }
  return Promise.resolve();
}

/**
 * Whether a bundled clip exists for this glyph.
 *
 * Synchronous and side-effect free, so it is safe to call during render — use
 * it to hide the "Hear it" affordance rather than offering a dead button.
 */
export function isKanaAudioAvailable(glyph: string): boolean {
  return glyph in KANA_AUDIO;
}
